# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Anti-Procrastinator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anti-Procrastinator
pod 'SCLAlertView'
use_frameworks!
pod 'SwiftCharts', '~> 0.6.3'

end
